### ISSUE TITLE
Diff doesn't show section changes / misleads on where changes appear

### ISSUE THREAD

**Issue by scarlac** [react-native-community/upgrade-helper#101]
# Bug
As screen in this screenshot, the context for the `!debug.keystone` change shows under the `"# IntelliJ"` section which is quite misleading. By looking at the line numbers you may notice that they are not linear - **there is a jump from line 25 to 39**. However there is no notice of this, so the context lines appears together with the wrong section header.

<img width="883" alt="Screen Shot 2019-10-04 at 13 51 53" src="https://user-images.githubusercontent.com/895369/66239560-0b043080-e6af-11e9-9f64-7591f443a458.png">

Since some changes are context sensitive, it may cause problems for people while upgrading. In this particular example (`.gitignore`) the context isn't important beyond readability and future upgrade diffs.

## React Native versions
0.60.6 => 0.61.2

<img width="659" alt="Screen Shot 2019-10-04 at 13 56 47" src="https://user-images.githubusercontent.com/895369/66239566-0fc8e480-e6af-11e9-898d-d2a516624315.png">

## Steps to reproduce
1. Open https://react-native-community.github.io/upgrade-helper/?from=0.60.6&to=0.61.2
2. Scroll down to the diff of .gitignore
3. See that "Android/IntelliJ" appears as the header for the Buck ignore changes.

Describe what you expected to happen:
There should be a visual divider or other visual clue when line numbers increment more than 1.

**Comment by pvinis** [comment]
😬 I've never seen that jump before. we should check this. thanks for reporting.

**Comment by lucasbento** [comment]
@scarlac: thanks for opening the issue but I don't really understand what the problem is here.

The diff that's rendered on upgrade-helper looks exactly the same as the one on GitHub:

#### GitHub
<img width="1220" alt="Screen Shot 2019-10-08 at 14 09 00" src="https://user-images.githubusercontent.com/6207220/66394362-38195180-e9d5-11e9-9d04-d5296d158c55.png">

#### Upgrade-Helper
<img width="1142" alt="Screen Shot 2019-10-08 at 14 08 55" src="https://user-images.githubusercontent.com/6207220/66394367-394a7e80-e9d5-11e9-9764-55e98a86199e.png">

Can you please elaborate a little more on what the issue is?

**Comment by kelset** [comment]
I think that the key differente is that in github you have the blue row "showing" that there is a lineskip/jump - while on UH it's shown without intermediate "skip". So someone could copy paste the #Android/IntelliJ section down to the new debug.keystore and just paste it over their code - and in doing that removing the content of lines 36->38 from their .gitignore

**Comment by lucasbento** [comment]
Ah, I see, thanks for the clarification, @kelset.

I think we can fix this on our side by adding a [Decoration](https://github.com/otakustay/react-diff-view/#add-decoration-around-hunks) or a [Widget](https://github.com/otakustay/react-diff-view/#add-widgets) after a diff hunk, a PR for this is more than welcome!

**Comment by KevinHu2014** [comment]
@lucasbento Is it something like this?

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/7204070/66590193-cbfc4080-ebc2-11e9-925a-94444275d496.png">

**Comment by pvinis** [comment]
Please make a PR :D

**Comment by KevinHu2014** [comment]
@pvinis 
Do we need the expend code button on the side? Or the screenshot above would be fine?

**Comment by kelset** [comment]
I think that as a starting point just the "blue row" is enough :) we can do the "expand" feature separately :)

**Comment by pvinis** [comment]
Yep. Let's keep it simple.

**Comment by lucasbento** [comment]
❤️

**Comment by pvinis** [comment]
Thank you @KevinHu2014! @scarlac you should be able to see this very soon, it is being built and deployed.

**Comment by scarlac** [comment]
Thanks guys 👌
