### ISSUE TITLE
remove snapshot tests

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#106]
We should remove the snapshot tests, at least for the general places. we should keep snapshots for specific UI things in the diff, but it makes little sense to test the main part, since it changes relatively often with new notes etc.

**Comment by lucasbento** [comment]
Can you open a PR for this?

**Comment by pvinis** [comment]
I just made this to not forget, because I was in the train :D I can make a PR a bit later if no one else jumps on this.
