### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by kelset** [react-native-community/upgrade-helper#11]
Now that we are getting closer to having a v1 ready, I am starting to wonder if we shouldn't change the name of the repo to something that more clearly tells what it is about.

I was thinking to changing the name to `upgrade-helper`, what do you think?

(also, we need to improve a bit the README, I can take care of it)

**Comment by lucasbento** [comment]
Would love some help with the README!

I was thinking about `upgrade-page` but `upgrade-helper` seems more suitable :)

**Comment by pvinis** [comment]
woop woop
