### ISSUE TITLE
make AppName warning better

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#113]
# Description
After #112, @lucasbento suggested some good changes:
- [ ] Have it appear only after the diff has been rendered
- [ ] Move it to be shown below the "Useful content" section
- [ ] Have the same width as the useful content section to maintain consistency
- [ ] Use "info" alert instead of "warning"
- [ ] Add a comment on it that the app name can be changed in the settings (this would happen in #111 probably)

@Naturalclar, since you have worked on both of these, we would be very happy if you wanted to pick these ones up too 🙌

**Comment by lucasbento** [comment]
Just added a couple more points, @Naturalclar let us know what you think 🙂

**Comment by Naturalclar** [comment]
These points all sounds good! I can pick these up :+1:

**Comment by lucasbento** [comment]
Done by @Naturalclar on #130 🙂
