### ISSUE TITLE
Add button to star project in GitHub

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#15]
# Feature Request

Add a button to star the project on GitHub, can be done using `react-github-btn`.

**Comment by pvinis** [comment]
https://github.com/react-native-community/upgrade-helper/blob/dd27ebd81e58a67737a6525b3bb1bcc2ecfdfee9/src/components/pages/Home/index.js#L47-L53

**Comment by pvinis** [comment]
done in #35
