### ISSUE TITLE
0.62.0-rc.0 not on left dropdown

### ISSUE THREAD

**Issue by safaiyeh** [react-native-community/upgrade-helper#154]
# Bug

## React Native versions
0.62.0-rc.0

## Steps to reproduce

Describe what you expected to happen:

1. I upgraded my app to 0.62.0-rc.0 previously 
2. Want to compare changes from 0.62.0-rc.0 to 0.62.0-rc.1
3. 0.62.0-rc.0 does not show up in the left dropdown
4. Current work around is to change URL params to https://react-native-community.github.io/upgrade-helper/?from=0.62.0-rc.0&to=0.62.0-rc.1

**Comment by pvinis** [comment]
Yup. I saw that too. I made #153 for now, while we fix it in a better way.

**Comment by lucasbento** [comment]
Thanks for reporting this @safaiyeh, we merged #153 and #157 that fix this, let us know if you find any other bugs.

**Comment by safaiyeh** [comment]
Awesome, great work guys! @pvinis @lucasbento
