### ISSUE TITLE
Add unified diff option

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#17]
# Feature Request

Some people may prefer to see the diff unified like GitHub provides, we should offer an option to do so.

**Comment by kelset** [comment]
True, but I feel that it's not a blocker for v1

**Comment by lucasbento** [comment]
No worries, we will stick to #10.

**Comment by iamrestrepo** [comment]
I can take this if nobody is working on it already.  😃

**Comment by iamrestrepo** [comment]
Done ✅  let me know if it requires any change/update. 😃

**Comment by lucasbento** [comment]
Fixed by @iamrestrepo on #87 🎉
