### ISSUE TITLE
Make the path of the file clickable for collapsing files

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#179]
# Feature Request

Currently only this is clickable to collapse a file:

![Screenshot 2020-02-28 at 11 07 50](https://user-images.githubusercontent.com/6207220/75539723-0869f500-5a1b-11ea-9dd9-f443d01c0eb4.png)

Would be really nice to get this area to be clickable as well:

![Screenshot 2020-02-28 at 11 08 44](https://user-images.githubusercontent.com/6207220/75539751-10c23000-5a1b-11ea-96b7-49500eb84331.png)

## Why it is needed

The collapse button is very small.

## Possible implementation

Wrap the button and the file path with a wrapper and pass [this](https://github.com/react-native-community/upgrade-helper/blob/master/src/components/common/Diff/DiffHeader.js#L179) `onClick` handler on it.

**Comment by bratsos** [comment]
I can take a look, is this still up for grabs? @lucasbento

**Comment by lucasbento** [comment]
@bratsos I think @felippepuhle is already working on it.

Can you confirm @felippepuhle?

**Comment by felippepuhle** [comment]
Yes, I'm sending the PR right now.
