### ISSUE TITLE
Scroll to Done section when clicking the CompletedFilesCounter

### ISSUE THREAD

**Issue by benomatis** [react-native-community/upgrade-helper#215]
# Feature Request
Scroll to Done section when clicking the CompletedFilesCounter (numbers in the bottom right hand corner).

## Why it is needed
The list of changes can sometimes be very long, so it would be great if, by a click of a button, one could quickly scroll to the top of the Done section to see what one has been through already, especially if one, by accident, may click the checkmark too quick. In fact, the first time I used this tool, I did click the numbers a couple of times before realising it's not doing anything.

## Possible implementation
Some sort of a `scrollTo` function, and I would be glad to do it but my time is limited, and, honestly, I have been struggling to get scrolling features right, so not really keen going back there. :)

**Comment by lucasbento** [comment]
Love this, would you be willing to send a PR @benomatis?

**Comment by benomatis** [comment]
@lucasbento It shoouldn't be long, normally, but I'm always warry about implementing scrolling, as one also has to think about what happens when someone starts manually scrolling while the auto-scrolling is happening, for example, and there might be other scenarios I haven't thought of... I'll try to find time for this ;)

**Comment by benomatis** [comment]
@lucasbento I created PR https://github.com/react-native-community/upgrade-helper/pull/216 for this. I guess we could close this issue and discuss the details in the PR.

**Comment by lucasbento** [comment]
Again, thank you for your contribution @benomatis!
