### ISSUE TITLE
Link to the repo

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#217]
The button to star is great, but I often click there to go to the repo, and then I need to click on the repo name to see the files. It would be great to add a github link to the repo directly as well.

**Comment by lucasbento** [comment]
@pvinis: what do you mean about this?

I'm asking because when you click on the `Star` button it goes straight to https://github.com/react-native-community/upgrade-helper.

**Comment by pvinis** [comment]
Oh wow. I actually clicked on `Star` the first time, and then I always clicked on the number next to it, out of fear I would unstar, so I kept clicking the number and then another click to go to the repo. I blame it on bad UI or bad pavlos brain 😆. I'll close this I guess 😅.

**Comment by lucasbento** [comment]
> Oh wow. I actually clicked on Star the first time, and then I always clicked on the number next to it, out of fear I would unstar, so I kept clicking the number and then another click to go to the repo. I blame it on bad UI or bad pavlos brain 😆. I'll close this I guess 😅.

Ahahaha this is such a funny user-case

For me I always disliked that the "Star" led to https://github.com/react-native-community/upgrade-helper as I always thought that it should go to https://github.com/react-native-community/upgrade-helper/stargazers, I had no idea that the number did that 😄
