### ISSUE TITLE
Add link to file in diff for binary change

### ISSUE THREAD

**Issue by guhungry** [react-native-community/upgrade-helper#22]
# Feature Request
Add Link to File in Diff panel so file can be download which will be useful for binary file update

## Why it is needed
For example when upgrade from `0.59.8` to `0.59.9`. File `android/gradle/wrapper/gradle-wrapper.jar` was upgrade but no diff due to it's a binary file.
![image](https://user-images.githubusercontent.com/4032276/59241757-1a103000-8c33-11e9-9410-cc2e63eb709a.png)

## Possible implementation
Add link to file for example [https://github.com/react-native-community/rn-diff-purge/raw/release/0.59.9/RnDiffApp/android/gradle/wrapper/gradle-wrapper.jar](https://github.com/react-native-community/rn-diff-purge/raw/release/0.59.9/RnDiffApp/android/gradle/wrapper/gradle-wrapper.jar)

**Comment by lucasbento** [comment]
Thank you for opening this issue, we are already keeping track of this at #10, going to open a PR this week :)

**Comment by lucasbento** [comment]
@guhungry: you can now download binary files!

<img width="1101" alt="Screen Shot 2019-06-12 at 20 37 08" src="https://user-images.githubusercontent.com/6207220/59377150-ed066f00-8d51-11e9-9434-7ae61e6a1d4e.png">

Thanks for opening the issue :)
