### ISSUE TITLE
Android package name does not update

### ISSUE THREAD

**Issue by safaiyeh** [react-native-community/upgrade-helper#227]
# Bug
I changed the app name in the settings; however, the package name is still the same.

<img width="885" alt="Screen Shot 2020-04-03 at 9 45 13 AM" src="https://user-images.githubusercontent.com/8675043/78385211-5cbf4200-7590-11ea-9daa-d6d210bf6aeb.png">

## React Native versions
0.62

## Steps to reproduce

Describe what you expected to happen:

1. Diff from 61.1 -> 0.62

2. Change app name in settings

3. New flipper file in Android should also include the app's package name

**Comment by SaeedZhiany** [comment]
a similar problem in ios file `project.pbxproj`
I have also submitted a [PR](https://github.com/react-native-community/upgrade-helper/issues/230) for it

**Comment by SaeedZhiany** [comment]
a similar problem in ios file `project.pbxproj`
I have also submitted a [issue](https://github.com/react-native-community/upgrade-helper/issues/230) for it

**Comment by SaeedZhiany** [comment]
a similar problem in ios file `project.pbxproj`
I have also opened a [issue](https://github.com/react-native-community/upgrade-helper/issues/230) for it
