### ISSUE TITLE
Upgrade hints will be disappeared when setting project name in the setting menu

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/upgrade-helper#228]
# Bug

I just noticed that upgrade hints will be disappeared when I set my project name in the setting menu

## React Native versions

from RN 0.59.10
to RN 0.62.2

## Steps to reproduce

1. choose RN 0.59.10 and 0.62.2 for upgrading 

2. write your project name in the setting menu (for example, PROJECTNAME)

3. click on `show me how to upgrade!`

4. check ios/PROJECTNAME.xcodeproj/project.pbxproj

5. you will see that the hints aren't shown on this file

![image](https://user-images.githubusercontent.com/13766432/78980920-1b9cd400-7b34-11ea-9b1f-a340daf6ed1b.png)

Describe what you expected to happen:

we must see the hints on this file just like when we don't configure project name in the setting menu like below

![Annotation 2020-04-10 135451](https://user-images.githubusercontent.com/13766432/78980352-fa87b380-7b32-11ea-93b7-b3bd7acd7a2f.png)

**Comment by lucasbento** [comment]
@SaeedZhiany thanks for reporting this issue, #264 fixes it.

Apologies for taking so long to fix it.

**Comment by SaeedZhiany** [comment]
Great!

Thanks, @lucasbento
