### ISSUE TITLE
Sticking the header of diff files

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/upgrade-helper#229]
# Feature Request

Sticking diffs file's header to the top when scrolling the bottom.

## Why it is needed

Some file changes are too big between two versions of RN. (for example `project.pbxproj` between RN 0.59.10 and 0.62.2) so we'll see a too long diff for the files.

It would be great if the header of the files stick to the top when we scrolling bottom, so the options collapsing the file diff and checkmark option will always be available and don't need to scroll to the very bottom to access to the options.

## Possible implementation

The feature should be achieved with some CSS styles.

### Code sample

I have no idea right now but I'll update my post if I find something.

**Comment by mhmdAljefri** [comment]
I'm able to do this

**Comment by SaeedZhiany** [comment]
@mhmdAljefri 

Nice, so submit a PR for it.
Thanks

**Comment by SaeedZhiany** [comment]
The feature has been added by @mhmdAljefri's PR. Thanks!

I'm closing this issue.
