### ISSUE TITLE
Improve issue and pull request templates

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#23]
# Feature Request

We need to have our own `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md`.

## Why it is needed

The repository is currently inheriting what is on [rn-community's .github](https://github.com/react-native-community/.github), those currently have react-native-only content.

## Possible implementation

Work on top of [rn-community's .github](https://github.com/react-native-community/.github).

**Comment by kelset** [comment]
Yeah this is more or a web project so probably we'd have to change a couple things around
