### ISSUE TITLE
ld: library not found for -lAppAuth clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by pastean** [react-native-community/upgrade-helper#232]
# Bug

ld: library not found for -lAppAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## React Native versions

0.61.5 to 0.62.2

## Steps to reproduce

Followed all the instructions and got to this point. I should mention that i've upgraded from 0.59.5 -> 0.60 -> 0.61 -> 0.61.5 -> 0.62.2. Now I'm stuck at the last bit.

The error is complaining about not being able to find that specific library. Previously there was also a warning right before this error stating that it's not being able to find the directory. I've fixed that by removing $(inherited) from Library Search Paths.

I've checked and that folder/library does in fact exist in that location

Describe what you expected to happen:

1. Successfully build the app

**Comment by kelset** [comment]
Hello there - for upgrade support, please visit this repo: https://github.com/react-native-community/upgrade-support
