### ISSUE TITLE
dev crash in android 4.4.2 with npx react-native init example

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [react-native-community/upgrade-helper#245]
![](https://user-images.githubusercontent.com/27407218/82621092-b21ce480-9c0c-11ea-827f-17272c780919.png)

![QQ截图20200522163320](https://user-images.githubusercontent.com/27407218/82648245-fbd7f000-9c49-11ea-9231-d483fa281dbe.png)

**Comment by AnOptimistSeePessimist** [comment]
but release version is ok in android 4.4

**Comment by kelset** [comment]
this is not an issue valid for this repo. Please open an issue on the main react native repo following the template (and maybe check what's the minimum version supported by RN because I think you are quite close to that)
