### ISSUE TITLE
Missing v0.62.3

### ISSUE THREAD

**Issue by taylorkline** [react-native-community/upgrade-helper#275]
# Bug

The [v0.62.3](https://github.com/facebook/react-native/releases/tag/v0.62.3) release notes link to the React Native Upgrade Helper tool, but this tool does not support upgrading specifically to v0.62.3.

## React Native versions

From any version below v0.62.3 to v0.62.3.

**Comment by pvinis** [comment]
Missed that! I just generated them. Thanks.
