### ISSUE TITLE
'View File' redirects to broken URL

### ISSUE THREAD

**Issue by yfunk** [react-native-community/upgrade-helper#279]
# Bug

Pressing the 'View file' button on any file in the Upgrade Helper redirects to a broken URL (e.g. [`https://github.com/undefined/raw/release/0.63.4/RnDiffApp/package.json`](https://github.com/undefined/raw/release/0.63.4/RnDiffApp/package.json)).

This bug seems to have been introduced very recently, because I remember it working a day ago.

## React Native versions

Any two versions (e.g. `0.63.4` to `0.64.2`)

## Steps to reproduce

- Open [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/)
- Choose any two versions and press the 'Show me how to upgrade!' button
- Press the 'View file' button on any file
- Broken URL is opened

Describe what you expected to happen:
- Valid URL is opened

**Comment by lucasbento** [comment]
Thanks for reporting @yfunk, this was introduced by #273, #280 should fix it.

**Comment by lucasbento** [comment]
All good now.

Again, thanks for reporting @yfunk!

**Comment by yfunk** [comment]
> 
> 
> All good now.
> 
> Again, thanks for reporting @yfunk!

No problem, thanks for the extremely fast fix 😄
