### ISSUE TITLE
Add release files for `0.57` and `0.58`

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#29]
# Feature Request

Add useful content section for `0.57` and `0.58`, these need to include the official blog post on React Native website and the following links for upgrading:

- https://reactnative.thenativebits.com/courses/upgrading-react-native/upgrade-to-react-native-0.57/
- https://reactnative.thenativebits.com/courses/upgrading-react-native/upgrade-to-react-native-0.58/

**Comment by kelset** [comment]
Actually there are noone for 0.57 & 58 😅

Only for 59 -> https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059

**Comment by lucasbento** [comment]
@kelset: I saw :P I'm adding only the links for upgrading and the changelog.

**Comment by lucasbento** [comment]
Fixed on #35.
