### ISSUE TITLE
Add a changelog link automatically after the versions are selected

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#31]
# Feature Request

Basically append a link to the useful content section for the changelog of each major bump.

**Comment by kelset** [comment]
You mean, like, the related link from here https://github.com/react-native-community/releases/blob/master/CHANGELOG.md ?

Or from https://github.com/facebook/react-native/releases?

**Comment by lucasbento** [comment]
@kelset: the first as I see that as the "complete one"

**Comment by kelset** [comment]
Gotcha, so something like https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0599 when you target 0599, right?

(also, this overlaps with #29 right?)

**Comment by lucasbento** [comment]
@kelset: exactly, I'm working on both now.

Currently it's going to show only for the versions that have the useful content section (`0.57`, `0.58`, `0.59` and soon `0.60`), I will do it later for other versions as I still need to find a place to put the link to the changelog.

**Comment by lucasbento** [comment]
Fixed on #35.
