### ISSUE TITLE
upgrade-helper website is not working

### ISSUE THREAD

**Issue by DeepakM02** [react-native-community/upgrade-helper#324]
# Bug
it seems due to the API website is not working. 
https://react-native-community.github.io/upgrade-helper/

## React Native versions

0.67.2 to 0.69

## Steps to reproduce

Describe what you expected to happen:

1. 

2.

**Comment by cortinico** [comment]
Works well on my end. Can you try this URL? https://react-native-community.github.io/upgrade-helper/?from=0.67.2&to=0.69.6
![Screenshot 2022-10-19 at 18 23 49](https://user-images.githubusercontent.com/3001957/196761806-97323527-0a7d-4edb-adf3-f08d3e10c8ed.png)

**Comment by pvinis** [comment]
solved
