### ISSUE TITLE
[iOS] Missing `ios/RnDiffApp.xcworkspace/contents.xcworkspacedata` file

### ISSUE THREAD

**Issue by cipolleschi** [react-native-community/upgrade-helper#328]
# Bug

Some versions of the upgrade helper are missing the `contents.xcworkspacedata`.

This is happening because the Ruby environment is not set properly and the script fails to:
1. install the dependencies.
2. create the expected files.

[Example failure](https://github.com/react-native-community/rn-diff-purge/actions/runs/3406030709/jobs/5672164639#step:7:683)

The script ignore the failure and proceeds with the job, publishing the diff anyway.

## React Native versions

- [0.63.5](https://github.com/react-native-community/rn-diff-purge/tree/release/0.63.5/RnDiffApp/ios)  - observe that the `RnDiffApp.xcworkspace/contents.xcworkspacedata` file is missing
- [0.64.4](https://github.com/react-native-community/rn-diff-purge/tree/release/0.64.4/RnDiffApp/ios) - observe that the `RnDiffApp.xcworkspace/contents.xcworkspacedata` file is missing
- [0.65.3](https://github.com/react-native-community/rn-diff-purge/tree/release/0.65.3/RnDiffApp/ios) - observe that the `RnDiffApp.xcworkspace/contents.xcworkspacedata` file is missing
- [0.66.5](https://github.com/react-native-community/rn-diff-purge/tree/release/0.66.5/RnDiffApp/ios) - observe that the `RnDiffApp.xcworkspace/contents.xcworkspacedata` file is missing
- [0.68.5](https://github.com/react-native-community/rn-diff-purge/actions/runs/3405884542/jobs/5664181889#step:7:673) - observe the failure in CI
- [0.69.7](https://github.com/react-native-community/rn-diff-purge/actions/runs/3406024386/jobs/5664426846#step:7:675) - observe the failure in CI
- [0.70.4](https://github.com/react-native-community/rn-diff-purge/actions/runs/3322235646/jobs/5490970703#step:7:669) - observe the failure in CI
- [0.70.5](https://github.com/react-native-community/rn-diff-purge/actions/runs/3406030709/jobs/5672164639#step:7:683) - observe the failure in CI
- [0.71.0-rc.0](https://github.com/react-native-community/rn-diff-purge/actions/runs/3395494978/jobs/5645450800#step:7:671) - observe the failure in CI

## Steps to reproduce

Run the script and see the Cocoapods failure.

## Suggested fix

The suggested fix would be to update the [new-release.sh](https://github.com/react-native-community/rn-diff-purge/blob/master/new-release.sh) script so that:

1. It installs [`rbenv`](https://github.com/rbenv/rbenv) (or a similar Ruby Management system
2. `curl` the right [Ruby version]() for ReactNative when releasing a new version. It should use the version tags to learn where to look. [Example for v0.70.X](https://github.com/facebook/react-native/blob/v0.70.0/.ruby-version)
3. Install the right ruby version
4. Set the ruby version as global version
5. Proceed with the standard execution.

As an additional safety net, the script should fail if the dependencies are not installed correctly, with a proper error message.

**Comment by kelset** [comment]
cc @pvinis @lucasbento - can you help us here in understanding how to approach this?

Aside from fixing it, we also need to understand what to do with the affected versions, is there a way to revert a version and regenerate it correctly?

---

cc @Aleksefo who noticed first, and reported [here](https://github.com/facebook/react-native/issues/35210#issuecomment-1305351936)

**Comment by pvinis** [comment]
I'll be back to a laptop tomorrow, and I'll check

**Comment by uzegonemad** [comment]
On a probably related note, going from 0.67.4 to 0.67.5 currently includes about 800 `vendor/bundle/ruby/*` files, which inevitably crashes the browser tab.

<img width="462" alt="Screen Shot 2022-11-07 at 11 47 09" src="https://user-images.githubusercontent.com/430255/200379234-61c655e1-41d6-46a8-9e93-4a351c5cb546.png">

**Comment by fabriziobertoglio1987** [comment]
Is the problem the ruby version? As documented in the link below, macOs 12.6.1 comes preinstalled with ruby 2.7.6, 3.0.4, and 3.1.2 (available to chruby).

https://circle-macos-docs.s3.amazonaws.com/image-manifest/v8824/index.html

>CircleCI macOS Container Software
>This document describes the software present on [CircleCI](https://circleci.com/) macOS containers.
>2.7.6, 3.0.4, 3.1.2 (available to chruby)

https://github.com/facebook/react-native/commit/21c8837c1264cd96f5899e33132fa764bb9c2293

https://github.com/react-native-community/rn-diff-purge/actions/runs/3406030709/jobs/5672164639#step:1:4

**Comment by fabriziobertoglio1987** [comment]
https://github.com/facebook/react-native/blob/35fa47b3828a5dbaceeca02f333cf3c4a147e3b7/template/Gemfile#L4

>error Your Ruby version is 3.0.4, but your Gemfile specified 2.7.5
https://github.com/react-native-community/rn-diff-purge/actions/runs/3406030709/jobs/5672164639#step:7:683

https://stackoverflow.com/a/37915028/7295772

https://circle-macos-docs.s3.amazonaws.com/image-manifest/v8824/index.html
>System Version | macOS 12.5.1 (21G83)
>Installed Rubies | 2.7.6, 3.0.4, 3.1.2 (available to chruby)

I would try to change in docker environment the currently ruby version to 2.7.6 see https://github.com/postmodern/chruby

but I'm not sure it will work




Installed Rubies | 2.7.6, 3.0.4, 3.1.2 (available to chruby)
-- | --

**Comment by fabriziobertoglio1987** [comment]
```bash
if [ $# -eq 1 ]; then
    VERSION=$1
else
    VERSION=$(ruby --version | cut -d' ' -f2 | cut -dp -f1)
fi


if [ -z "$VERSION" ]; then
    die "Please provide an installed/usable Ruby version"
fi
echo "Setting Ruby version to: $VERSION"


cd "$ROOT" || die "Failed to change to $ROOT"


# do this first, so rbenv/rvm will automatically pick the desired version
echo "$VERSION" > .ruby-version
```
https://github.com/facebook/react-native/blob/0a3ca80af401654896cbc73e235711eef0f9b3c5/scripts/update-ruby.sh#L26-L40

The installation will use the existing ruby version in your environment, as you are using 12.5.1 it will be 3.0.4

**Comment by pvinis** [comment]
Alright. I just read the whole thing here.

- First, the `contents.xcworkspacedata` file is ok to be missing. It is a file that is generated by Xcode when a workspace is opened/used. Here's an [example](https://github.com/artsy/eigen/blob/main/ios/Artsy.xcworkspace/contents.xcworkspacedata). It holds no important info from RN, and it will be generated when/if needed. Nothing the upgrade-helper or people upgrading should care about.

- Second, I see the ruby issue. Definitely a problem, I'll try to fix it and report back.

- Third, I see the vendor files, I will try to address this first, as it seems like the most blocking thing.

**Comment by pvinis** [comment]
Vendor stuff gone. I manually removed some. Seems like it was only on that specific upgrade to `0.67.5`. Fixed and pushed. https://react-native-community.github.io/upgrade-helper/?from=0.67.4&to=0.67.5 and others work as expected again.

fun 😅 
<img width="353" alt="Screenshot 2022-11-12 at 00 59 12" src="https://user-images.githubusercontent.com/100233/201448985-ca6a3a93-d939-4ebe-b0f6-a24be8418f9e.png">

I think I will also rebase so we can work with the diffs easier.

**Comment by pvinis** [comment]
I regenerated the problematic `0.67.5` too, so now the new diffs will not have any vendor stuff in the diffs.

**Comment by pvinis** [comment]
Ruby issue fixed too. I used asdf in the github-action here https://github.com/react-native-community/rn-diff-purge/blob/master/.github/workflows/new_release.yml, should be fine on the next diff generation. lets keep an eye!

**Comment by pvinis** [comment]
I think I will close this issue, and lets open it up again if any of the above is not clear or not working. I feel confident for everything, though.
