### ISSUE TITLE
Upgrade from 0.66.5 to 0.67.5 is very slow till browser freeze/crash

### ISSUE THREAD

**Issue by pke** [react-native-community/upgrade-helper#329]
# Bug

https://react-native-community.github.io/upgrade-helper/?from=0.66.5&to=0.67.5

It will eventually resolve a ton of changes and render the page but scrolling crashes the browser frame (Chrome).

**Comment by pvinis** [comment]
solved

**Comment by pke** [comment]
Thanks, can you share a short insight how it was fixed?
