### ISSUE TITLE
Drop down not showing versions list

### ISSUE THREAD

**Issue by deepu-varghese** [react-native-community/upgrade-helper#333]
# Bug

The drop down which loads the versions list keeps loading. No list of versions is displayed.

![Screenshot 2022-12-06 at 11 10 49 AM](https://user-images.githubusercontent.com/77835067/205827932-9b6fbff7-b975-4e9d-b078-7c89a9b5b890.png)

## React Native versions

0.66 to 0.68

## Steps to reproduce

Check the working of https://react-native-community.github.io/upgrade-helper/

Describe what you expected to happen:

1. The site should display the list of versions.

**Comment by deepu-varghese** [comment]
> Facing the same issue on my mac.

Same here. Not loading on my mac

**Comment by deepu-varghese** [comment]
looks like some network specific issue. Seems to be working with other networks.

**Comment by supriyo-credain** [comment]
facing the issue . any solutions ?
