### ISSUE TITLE
https://react-native-community.github.io/upgrade-helper is down

### ISSUE THREAD

**Issue by mansdahlstrom1** [react-native-community/upgrade-helper#354]
# Bug

The tool is currently down: https://react-native-community.github.io/upgrade-helper 

ERR_SSL_PROTOCOL_ERROR

**Comment by adsalihac** [comment]
Always down ?

**Comment by KevinHu2014** [comment]
Hi @mansdahlstrom1 @adsalihac, I hope you're doing well.
I wanted to check in and see if the issue earlier is still ongoing.
(If not, let's consider closing the issue)

**Comment by milanvaland** [comment]
Its still down, this API is getting timeout **ERR_CONNECTION_TIMED_OUT**
https://raw.githubusercontent.com/react-native-community/rn-diff-purge/master/RELEASES
@KevinHu2014

**Comment by adsalihac** [comment]
Sometime it is working , current time it is not working

**Comment by AdarshJais** [comment]
down again!

**Comment by dfeliz** [comment]
It's down again 🤔 seems unstable. I get a timeout.

**Comment by ahlbet** [comment]
Down today with `TypeError: Invalid Version: 500: Internal Server Error` error in console

**Comment by kailashkumar210** [comment]
I tried this DNS `8.8.8.8` and it worked.

**Comment by beingArkReal** [comment]
Down

**Comment by aadityapaliwal94** [comment]
When it will be up? Any time?
