### ISSUE TITLE
App name field reverts to placeholder each time "Show me how to upgrade" button pressed

### ISSUE THREAD

**Issue by smallsaucepan** [react-native-community/upgrade-helper#366]
# Bug

One great feature of the upgrade helper is the ability to enter your own app name instead of the default RnDiffApp and have the diffs customised to what you would expect to see. However, if you have entered a custom name and press the "Show me how to upgrade" button, the name field is cleared.

This then requires filling out the field again if wishing to regenerate the diffs based on other different criteria e.g. RN versions. This happens quietly meaning the user may generate a second set of diffs and start working through them, only to realise the app name in their diffs is now incorrect.

## React Native versions

n/a

## Steps to reproduce

Fill out the app name field with a custom name e.g. MyApp, press the "Show me how to upgrade" button

Describe what you expected to happen:

1. Ideally, the name field should retain your custom app name (MyApp). Instead it quietly reverts to RnDiffApp

**Comment by smallsaucepan** [comment]
@lucasbento / @pvinis would one of you like to assign this to me? Have forked and will return with a PR.

**Comment by pvinis** [comment]
feel free to open up a PR about this too 👍

**Comment by smallsaucepan** [comment]
Thanks for merging @pvinis 👍

**Comment by bz-bstk** [comment]
Hi @smallsaucepan thank you, this is a great feature. Just one question is when  I input the app name and app package, there is no different, the generated files still using 'RnDiffApp', any idea about this?  Thanks
