### ISSUE TITLE
Diff of `MainActivity.kt` is wrongly displayed (3x concatenated)

### ISSUE THREAD

**Issue by cortinico** [react-native-community/upgrade-helper#377]
# Bug

The diff of `MainActivity.kt` is wrong for 0.74:
https://react-native-community.github.io/upgrade-helper/?from=0.73.4&to=0.74.0-rc.0

It seems like if the diff is calling `cat` on the file 3 times? Not sure what's going on:
![Screenshot_2024-02-23_at_17 29 49](https://github.com/react-native-community/upgrade-helper/assets/3001957/05407a04-3da5-4486-9081-e1a9667edfd5)

## React Native versions

0.73.4 to 0.74.0-rc.0

## Steps to reproduce

Just go to https://react-native-community.github.io/upgrade-helper/?from=0.73.4&to=0.74.0-rc.0

Describe what you expected to happen:

1. Ideally I'd like to see the correct diff for the file.

**Comment by blakef** [comment]
I think there's some funk going on with the way we're normalising hunks.

**Comment by cortinico** [comment]
Fixed by #378
