### ISSUE TITLE
Add reference to upgrade-helper in other places

### ISSUE THREAD

**Issue by kelset** [react-native-community/upgrade-helper#38]
We should have a direct reference to this tool in other places like:
- [x] documentation (https://facebook.github.io/react-native/docs/0.59/upgrading) - @lucasbento
- [ ] maybe the main readme? or the wikis?
- [ ] react-native-releases?
- [ ] rn-diff-purge?

**Comment by pvinis** [comment]
For purge we have it as the main repo link, as well as a link close to the top on the readme, but we can make it more prominent if we want.

Another place should be the changelog on github with each release, minor or patch.

**Comment by lucasbento** [comment]
Love the changelog idea, can be linked with URL `/from={PREVIOUS_VERSION}&to={LATEST_VERSION}`.

**Comment by kelset** [comment]
yeah, tbh we should add it in the releases tab from 0.60.0 on

**Comment by lucasbento** [comment]
@kelset: would you be able to focus on this and let us know what you need help with?

**Comment by kelset** [comment]
for the releases tab, yeah - since I'm one of the few who can actually edit those 😅

for the others the more help we can get, the better, I'm super busy 😓

**Comment by lucasbento** [comment]
Cool, once I'm back I'm gonna see what I can tackle.

By main readme do you mean the one from RN?

**Comment by kelset** [comment]
Yeah - I can sort of do that too if it's easier.

I just need to remember, next week I should have time 😅

**Comment by lucasbento** [comment]
I'll work on the react-native-website one, should have a PR there this week.

**Comment by kelset** [comment]
Likely, both.

**Comment by lucasbento** [comment]
This seems to be done, shall we close it? 😄

**Comment by kelset** [comment]
yeah :) Unless there is something I forgot 😂

**Comment by lucasbento** [comment]
Should be good, let's open another issue if we remember something else.

Thanks for the work on this @kelset & @pvinis ❤️
