### ISSUE TITLE
RN 0.74 adds deprecated yarn-1.22.22.cjs

### ISSUE THREAD

**Issue by hristo87** [react-native-community/upgrade-helper#385]
# Bug

In the latest React Native update (version 0.74), the documentation indicates a transition to Yarn 3.x for new projects (as seen in the attached image). However, upon using the helper, a yarn-1.22.22.cjs file is added, and the .yarnrc file points to this file. Given that the documentation explicitly states the deprecation of Yarn 1.x in favor of 3.x, is this inclusion of the yarn-1.22.22.cjs file expected? Additionally, the file was not present initially but was added at a later time. Could you provide clarity on this discrepancy?

## React Native versions

0.74

## Steps to reproduce

update react native from 0.73.6 to 0.74

Describe what you expected to happen:

1. This file should not be included!

![image](https://github.com/react-native-community/upgrade-helper/assets/102364045/c05f33d1-c3d4-4ff6-bf14-12b0d9329d2e)

**Comment by cortinico** [comment]
cc @szymonrybczak

**Comment by szymonrybczak** [comment]
hey @hristo87! yes, you're right. There was a regression that in some scenario CLI didn't bump Yarn to 3.x → it's already [addressed](https://github.com/react-native-community/cli/pull/2367) and will be released with React Native 0.74.1. 

Re: Upgrade helper → PR with fix is waiting: https://github.com/react-native-community/rn-diff-purge/pull/75

**Comment by hristo87** [comment]
Thank you for clarifying this!
