### ISSUE TITLE
Comments not selected?

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#39]
I don't know if this can be done, but we should have a way to have the comments not mess with selection and copy-pasting.

Some people write the code manually, and some copy-paste from the diff. If there is a comment or more in there, then they also get selected and copied. Is there a way to make the text of the comment not selectable so copy-paste works easily?

If not, should we maybe add a way to quickly toggle them on and off?

**Comment by kelset** [comment]
Ah yeah this is a great point - yeah maybe a checkbox at the top for like showing comments/don't show them?

**Comment by lucasbento** [comment]
This is a good point, I believe there's a way to do it but we need to do some research, if it's too hard to do it let's fallback to @kelset suggestion.

**Comment by vinnyA3** [comment]
I'll take a look @ this and run a solution by you all.  I have an idea with CSS that should work here
