### ISSUE TITLE
Move the file after it's completed

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#43]
# Feature Request

This is related and started at #10, basically the website needs to show the "completed" files below the uncompleted ones.

## Why it is needed

It's easier this way to know which files are still left to be changed.

## Possible implementation

Have two sections of file _groups_, one for completed and another for uncompleted.

The project already stores the IDs of the completed ones [here](https://github.com/react-native-community/upgrade-helper/blob/643966b134372e962fe1e0518ccd50f474dd881b/src/components/common/DiffViewer.js#L26-L33).

**Comment by lucasbento** [comment]
cc @KevinHu2014 :)

**Comment by KevinHu2014** [comment]
Hi @lucasbento, Should I wait for #30 to be done, before sending the PR ?


## Quick Demo
Here's a quick Demo of what I did so far.
 (Sorry for making this in a video format. I try to make it a gif, but the quality is awful 😞)

[![Demo](https://imgur.com/RT7qtkq.png)](https://vimeo.com/345329101)

Would love some feedback on this :)

**Comment by lucasbento** [comment]
@KevinHu2014: that looks really good! 🔥 

The one for #30 shouldn't affect this so you are free to open a PR :)

The only things that I would change are the `Uncompleted section` and `Completed titles` as I don't think they are needed, the same goes for the `click ✅ as completed`.

@pvinis & @kelset: what do you think about this?

**Comment by kelset** [comment]
Thanks for your work @KevinHu2014, that video preview is 🔥

In terms of the titles for the sections, I actually think it's useful to have something clearly stating what's what. Maybe it's just a matter of copy? 🤔

The only minor nitpick (so don't worry too much about it) on my side would be to change the ✅ on a done file to something like a ↩️. Maybe with having there would be less of a need for the titles?

Feel free to open the PR :)

**Comment by pvinis** [comment]
Oh this is so gooooood!

I would add to the thing people said above, that we can use the ↩️ on mouseover on the green checkmark of a completed file. This way it should be clear that it will become undone again.

Also "uncompleted" sounds weird even though it's correct. Maybe "done"/"undone" is better, and then when all files are done we can have a little message "your upgrade is done!", so the copy fits all together?

Basically, awesome job 💜

**Comment by KevinHu2014** [comment]
Thanks for the feedback everyone! I'll send a PR later :)

To summarize:
+ Leave the titles to make it clearly stating what's what, but change the phrase to "done"/"undone".
+ Remove `click ✅ as completed`, and use the ↩️ on mouseover on the green checkmark of a completed file instead.
+ Having a little message "your upgrade is done!" when all files are done.

Huge thanks for being so nice to the newcomer ❤️
