### ISSUE TITLE
Add a "how to use" section

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#45]
# Feature Request

Working on facebook/react-native-website#1063 I noticed that we lack a "getting started"/"how to use" guide for the user to know what to do once they land on the page.

## Why it is needed

So it's more clear to the user what they need to do with that beautiful diff that's showing in their browser.

## Possible implementation

A button with a `?` icon that opens a modal with some nice content about how to upgrade using Upgrade Helper, content can be based on facebook/react-native-website#1063.

**Comment by kelset** [comment]
Yeah, this sounds like a good approach - probably just a few lines explaining👍

**Comment by KevinHu2014** [comment]
Could I have this one :)


By the way, Where should this button belongs?
Will it be nice if placing it besides the Github star badge button?
> A button with a ? icon that opens a modal with some nice content about how to upgrade using Upgrade Helper

**Comment by lucasbento** [comment]
@KevinHu2014: of course!

I was thinking more like putting it on the top right of the container, something like here:

<img width="654" alt="Screenshot 2019-07-03 at 09 52 50" src="https://user-images.githubusercontent.com/6207220/60573663-5d644700-9d78-11e9-92f9-73a1eabccf83.png">

But I suppose it would also look nice close to the star button, any of the two solutions would work well in my opinion.

**Comment by KevinHu2014** [comment]
Sorry I forgot this one. 😓

@lucasbento Shall we discuss the short version content of "How to use" first?
And since https://github.com/react-native-community/upgrade-helper/pull/91#issuecomment-524590639, the how to button still goes to top right of the container right?

**Comment by vinnyA3** [comment]
Hi @KevinHu2014

I think the top right corner is a nice position.  It can go right next to the settings button. What do you think @lucasbento?

**Comment by lucasbento** [comment]
> I think the top right corner is a nice position. It can go right next to the settings button. What do you think @lucasbento?

Oh yeah, definitely agree with this!

I would start doing this after #91 is merged, @KevinHu2014.

**Comment by pvinis** [comment]
The talk is out where I explain how to use this. Should we link to that? 😬

**Comment by kelset** [comment]
100% :)

**Comment by lucasbento** [comment]
> The talk is out where I explain how to use this. Should we link to that? 😬

Would be nice!

@KevinHu2014: you can also use https://facebook.github.io/react-native/docs/upgrading#upgrade-helper as reference.
