### ISSUE TITLE
Show `rc` versions in the `from` dropdown

### ISSUE THREAD

**Issue by pvinis** [react-native-community/upgrade-helper#49]
We show `rc` versions on the `to` dropdown until the final release is out.
After the final is out, if a user is on an `rc` version, they should be able to upgrade from that to the final.

Therefore we should show the `rc` versions on the `from` dropdown.

(If we want to minimize noise, we should only show the `rc`s of the latest version.)

**Comment by vinnyA3** [comment]
I'll pick this one up!

**Comment by lucasbento** [comment]
Awesome @vinnyA3, please let us know if you need any help 🙂

**Comment by vinnyA3** [comment]
Will do!

**Comment by vinnyA3** [comment]
Sorry @lucasbento @pvinis about the delay ... getting the feature in now
