### ISSUE TITLE
Add download link to all files

### ISSUE THREAD

**Issue by guhungry** [react-native-community/upgrade-helper#50]
# Feature Request
Add download link to all files

## Why it is needed
Sometime files can be replace directly (`.flowconfig`) or in case of new file (`.eslintrc.js`). Download and replace it would be faster.

## Possible implementation
Add download link just like binary file

**Comment by pvinis** [comment]
To be honest I feel like non-binary files don't need to be downloaded. I would prefer to have a "copy" button that copies the text, but this happens so infrequently that I don't think it's a problem.

Also, we encourage people to know and understand the changes, and even if you copy paste, you will still see something. Just downloading a file or many, I don't see this bringing any good.

Does that make sense?

**Comment by guhungry** [comment]
Umm, make sense. But how about link to `VIEW` source file in github.

Sometimes copy chunk of continuous text is not easy.
<img width="1184" alt="Screen Shot 2019-07-04 at 22 20 27" src="https://user-images.githubusercontent.com/4032276/60676835-18403200-9eaa-11e9-8610-94d2053cce14.png">
<img width="1172" alt="Screen Shot 2019-06-18 at 21 38 07" src="https://user-images.githubusercontent.com/4032276/60676878-35750080-9eaa-11e9-84d7-7fd289618d10.png">

**Comment by lucasbento** [comment]
🤔 I do like the option to view the entire source of the file.

@guhungry: do you think it should go directly to the raw file like GitHub does?

By the way, having a "copy" button to copy all the contents of the file will be slightly tricky to implement as we don't have the content of the file in hand, therefore we will need to first fetch all the content and then copy it to the clipboard. We could do it if proved to be efficient 🙂

**Comment by guhungry** [comment]
> @guhungry: do you think it should go directly to the raw file like GitHub does?
Either one is fine.

For copy feature `copy this chunk` would be great since data is already in diff.

**Comment by lucasbento** [comment]
@pvinis: what do you think about this?

**Comment by pvinis** [comment]
Hm, with all this info, yea, maybe it's nice to just put a link to the raw file on github. I'm not psyched about this, but let's do it and if later we find a better way, we decide.

**Comment by lucasbento** [comment]
@guhungry: I just noticed that the library we use has a prop to optimize what you select in the changes and I opened a PR to add it: https://github.com/react-native-community/upgrade-helper/pull/55, with this you can select changes on each column separately.

Thank you for bringing this up 😄

**Comment by lucasbento** [comment]
With #55, do you think "downloading files" or "copying chunks automatically" are still needed, @guhungry & @pvinis?

**Comment by pvinis** [comment]
Personally, I would never "download" a file from the diff.

If you guys think the option is important, then let's add it and let the people who were gonna use it, use it. I'm just afraid to make it "easier", when people start downloading and replacing their files, and then not actually looking at their own diffs after the upgrade and compare. The upgrade unfortunatelly needs care and attention, and I am hesitant to give people a footgun when they don't need it, even if they might ask for it.

But I'm open to be convinced otherwise :D

**Comment by lucasbento** [comment]
@pvinis: definitely agree with that!

**Comment by guhungry** [comment]
Working manual selecttion is more critical for me. For copy chunk is jus nice to have.

For download just as @pvinis said.

**Comment by pvinis** [comment]
Then maybe we just close this, since we merged the selection PR, and we can keep the other issue for downloading binary files?

**Comment by lucasbento** [comment]
Well, I would say we close this and if we see the need for the download button or copy chunks later on we can just create another issue, hope it's okay @guhungry.

Thanks for opening this issue, by the way! And thanks for the help @pvinis 🙂
