### ISSUE TITLE
Test automatically on different browsers

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#53]
# Feature Request

We should test the website automatically on multiple browsers.

## Why it is needed

With #51 being opened (thank you for this @KevinHu2014), it came to my attention that we should properly test the website on multiple browsers, the best way to do it would be to run a few tests automatically on CircleCI.

## Possible implementation

~~We can use [Cypress.io](https://docs.cypress.io/guides/guides/continuous-integration.html#Basics) with CircleCI, we can also think about a few image snapshots to do image comparison, which is an easier way to get things going for now.~~

Apparently Cypress supports only Chrome, we may consider using Sauce Labs (where we can run on multiple browsers) and [WebdriverIO](https://webdriver.io/) together with [wdio-image-comparison-service](https://github.com/wswebcreation/wdio-image-comparison-service).

I recall seeing a tweet that [now](now.sh) also had a plugin/extension for doing image comparison on PRs, let's see if I find more info about that.

**Comment by iamrestrepo** [comment]
If we aren't in a rush to implement this, I can take it (make take me a couple of weeks).  @lucasbento @kdenz

**Comment by lucasbento** [comment]
@iamrestrepo we are definetely in no rush to implement this, I appreciate that you want to work on it!

Let me know if you need any help with anything.

**Comment by iamrestrepo** [comment]
Status: Currently working on this!

**Comment by lucasbento** [comment]
Awesome @iamrestrepo 🙌 
Do you need any help?

**Comment by iamrestrepo** [comment]
Not so far @lucasbento . I will ask as I move farther along!
