### ISSUE TITLE
Show skeleton instead of spinner when loading the diff

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#58]
# Feature Request

This has been brought up by @RubenSandwich on #57, basically show a nice [skeleton](https://css-tricks.com/building-skeleton-screens-css-custom-properties/).

## Why it is needed

Spinner is ugly, long live the nice skeletons.

## Possible implementation

We can use something like [react-content-loader](https://github.com/danilowoz/react-content-loader).

**Comment by iamrestrepo** [comment]
@RubenSandwich are you working on implementing the skeleton loader? If not I can help. :)

**Comment by RubenSandwich** [comment]
@iamrestrepo Feel free to take it. I won't have the time until at least next week. :(

**Comment by iamrestrepo** [comment]
I will work on it.

**Comment by iamrestrepo** [comment]
Update: I am almost done with this, I will have a PR ready by the end of the week!

**Comment by lucasbento** [comment]
@iamrestrepo: awesome! please let us know if you need any sort of help 🙂

**Comment by KevinHu2014** [comment]
Shall we close this?

**Comment by kelset** [comment]
Yeah, the feature got merged :)
