### ISSUE TITLE
Add libraries to "Acknowledgments" section on README

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#63]
# Feature Request

This project isn't just based on CRA, it basically would take much longer to build if the amazing [react-diff-view](https://github.com/otakustay/react-diff-view) didn't exist and some crazy amount of work would be needed if [inline-mdx.macro](https://github.com/hamlim/inline-mdx.macro) wasn't out there (which we don't have implemented yet but @hamlim is doing a ton of work to support our structure).

We should add both projects to the `README.md` in appreciation to @otakustay and @hamlim's work.

**Comment by bethea28** [comment]
Hi! I got this one!!!

**Comment by lucasbento** [comment]
Awesome @bethea28!

**Comment by lucasbento** [comment]
Fixed by @bethea28 on #69, thank you so much for doing it!
