### ISSUE TITLE
Add the ability to collapse/expand all files for easy navigation.

### ISSUE THREAD

**Issue by Jeanmsilva89** [react-native-community/upgrade-helper#65]
# Feature Request

Allow users to collapse/expand all files at once. 

## Why it is needed

Makes it easier to find the right file on a large diff.

## Possible implementation

Hold `alt` and click on the inverted caret icon. It works as a toggle. 

https://github.blog/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/

**Comment by kelset** [comment]
Ah yeah, I've been thinking about something like this - sounds like a good idea 🤗

If you can open a PR it would be great :)

**Comment by lucasbento** [comment]
Whoa, that's pretty cool, would love to review a PR for this!

**Comment by lucasbento** [comment]
Closing this as it has been done on #74, thanks again @Jeanmsilva89! 🙂
