### ISSUE TITLE
Consider renaming the app_name to match the RN template and simplify the diff

### ISSUE THREAD

**Issue by rszalski** [react-native-community/upgrade-helper#67]
# Feature Request

Currently the diff is made between an RN app named `RnDiffApp` and the RN template which has a different app_name/DisplayName of `Hello App Display Name`. When upgrading this shows as 2 additional diffs that are IMO not necessary, see the SS:

![rn_upgrade_helper_app_name_diff](https://user-images.githubusercontent.com/184806/61518068-111c3680-aa09-11e9-848c-220671857c4b.png)

I propose we handle this name discrepancy so that it doesn’t show up in the diff.

## Why it is needed

Every upgrade shows at least 2 diffs that will (always?) be ignored. This unnecessarily increases the cognitive load for each upgrade.

## Possible implementation

I thought the change would be as simple as running `react-native init „Hello App Display Name”` but the `projectName` does not allow spaces. One solution that comes to mind is replacing `RnDiffApp` (which is a fairly specific string) with `Hello App Display Name`. However I’m not sure if we want to add this to the workflow.

Another option would be to submit a patch directly to https://github.com/facebook/react-native/tree/master/template and change the name to something like `HelloWorld`. This doesn’t feel right, though :)

Let me know if this makes sense and if you have better options on how to handle this.

**Comment by lucasbento** [comment]
@rszalski: thank you for opening this issue, I completely agree that we should handle cases like this.

@pvinis: Can you confirm if this is an error on generating the diff on `rn-diff-purge` or something on the CLI that's not replacing the name correctly?

**Comment by lucasbento** [comment]
This is related to react-native-community/cli#561.

**Comment by pvinis** [comment]
It is a bug in the cli scripts. I can manually go and remove this from the diffs, and maybe I'll do it, but it's easier to just regenerate the diffs once the cli is fixed. It's a small change that we can probably add a comment that it's not really relevant.

**Comment by pvinis** [comment]
https://github.com/react-native-community/upgrade-helper/pull/71

**Comment by pvinis** [comment]
https://github.com/react-native-community/cli/issues/561

**Comment by lucasbento** [comment]
@rszalski: we added a small comment on the files explaining that this change must be ignored, it's currently being tracked at react-native-community/cli#561 as mentioned before and as soon as it's fixed on the CLI we will update the diff and remove the note.

Again, thank you for opening this issue.
