### ISSUE TITLE
Line numbers are copied

### ISSUE THREAD

**Issue by JohanADT** [react-native-community/upgrade-helper#68]
# Bug

When I copy code from the upgrade helper and paste it into my editor, the line numbers are also copied.

![linenumbers](https://user-images.githubusercontent.com/42940811/61528882-d4a40700-aa17-11e9-9195-6f8268d59daa.gif)

# Info
Safari: 12.1.1 (14607.2.6.1.1)
VS Code: 1.36.1 (1.36.1)

**Comment by lucasbento** [comment]
This only happens on Safari, on Chrome it works as expected.

This looks like a bug with the library we use but I'm gonna look deeper just to make sure, thanks for filling this issue @JohanADT & @Johan-dutoit! (😜)

**Comment by Johan-dutoit** [comment]
@JohanADT Such a great guy for reporting these errors!

**Comment by mausworks** [comment]
Safari is the new Internet Explorer anyone?

**Comment by pvinis** [comment]
Yea safari is all kinds of broken here.
![Aug-07-2019 13-34-34](https://user-images.githubusercontent.com/100233/62619916-315c5880-b918-11e9-810d-b758f7866f59.gif)
It's also selecting left and right at the same time..

**Comment by KevinHu2014** [comment]
It seems to related to Chrome and Safari have different behavior when copying texts styled `user-select: none` . 

Here's the reference https://github.com/otakustay/react-diff-view/issues/62 .

**Comment by pvinis** [comment]
this is fixed. closing.

**Comment by Mazztwo** [comment]
This is NOT fixed on latest Safari v16.3

**Comment by Mazztwo** [comment]
> this is fixed. closing.

This is NOT fixed on latest Safari v16.3 @pvinis
