### ISSUE TITLE
CircleCI is not running jobs on forks

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#70]
# Bug

CircleCI is not running jobs on forks that are not trusted, we need to follow https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/ to only enable `test` and `lint` scripts to run on untrusted forks, `deploy` should remain the same.

**Comment by vinnyA3** [comment]
I can tackle this one! @lucasbento

**Comment by lucasbento** [comment]
Should be fixed #89.
