### ISSUE TITLE
Add Netlify to deploy on each PR

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/upgrade-helper#72]
# Feature Request

We should add and configure Netlify to deploy on each PR so we have an URL to preview the PR without having to do it manually and locally.

## Possible implementation

We can base the config on [react-native-website](https://github.com/facebook/react-native-website/blob/master/netlify.toml)'s and will only use it for PRs, we will remain using GitHub pages for `master` as we want to keep the URL under `react-native-community`.

**Comment by bethea28** [comment]
@here I’ll take this one on !

**Comment by lucasbento** [comment]
@bethea28: awesome, please let me know if you need any help 🙂

**Comment by bethea28** [comment]
@lucasbento hey I actually do need a little help..as easy as this task seems...there is something that I missing. Below I have screenshots of my packages.json. Yarn predeploy is what builds my build folder. I also have a screenshot of the errors that I am getting from Netlify.

<img width="1440" alt="Screen Shot 2019-08-04 at 10 05 39 PM" src="https://user-images.githubusercontent.com/19527299/62434194-a277f200-b705-11e9-9a75-4f258477bf64.png">
<img width="1440" alt="Screen Shot 2019-08-04 at 10 16 56 PM" src="https://user-images.githubusercontent.com/19527299/62434195-a277f200-b705-11e9-9e7e-5739e6ce3e7c.png">

**Comment by lucasbento** [comment]
@bethea28: can you open a PR with your final changes so I can check it out locally?

**Comment by lucasbento** [comment]
Sorry, just noticed that #84 is open, gonna check it!

**Comment by lucasbento** [comment]
Closing this as it's done, thanks for the help @bethea28!
