### ISSUE TITLE
The step related to react_native_config.xml is not being shown

### ISSUE THREAD

**Issue by yaronlevi** [react-native-community/upgrade-helper#77]
When using the tool with **0.55.0 -> 0.59.1**
The steps about react_native_config.xml is shown.

But,

When using the tool with **0.55.0 -> 0.59.2**
The steps about react_native_config.xml **is not shown**.

**Comment by lucasbento** [comment]
Thanks for reporting this, gonna check it out!

**Comment by KevinHu2014** [comment]
@yaronlevi @lucasbento 

It's seem that from **0.59.1 -> 0.59.2**  
`react_native_config.xml` was removed.

see the follow link:
https://react-native-community.github.io/upgrade-helper/?from=0.59.1&to=0.59.2

So  `react_native_config.xml` didn't shown.
> When using the tool with 0.55.0 -> 0.59.2
The steps about react_native_config.xml is not shown.

**Comment by lucasbento** [comment]
@KevinHu2014: thanks for checking this out.

@pvinis: can we confirm that this is not related to upgrade-helper?

**Comment by pvinis** [comment]
yes, it's all correct. the file was created and then removed. so upgrading from 55 to the version without the file, doesn't need to show that XML file

**Comment by lucasbento** [comment]
I would say we can close this then as the upgrade-helper is showing the correct diff.

Thanks for opening this issue @yaronlevi and thanks for checking this @KevinHu2014 & @pvinis.
