### ISSUE TITLE
entire contents of file being updated?

### ISSUE THREAD

**Issue by oxbits** [react-native-community/upgrade-helper#78]
# Question

First, thank you for the awesome app!

When using the app:

https://react-native-community.github.io/upgrade-helper/?from=0.58.6&to=0.59.10

it tells me to update this file:

`babel.config.js`

I do not have that file and there is no way to see what the entire file should look like in the update app.

I looked for it in the react native repo but I could not find it.

Not sure what to do.

**Comment by oxbits** [comment]
fyi: i did this:

`react-native init blank_project --version react-native@0.59.10`

and then copied over the file:

`babel.config.js`

thanks again

**Comment by matt-oakes** [comment]
👋 You may have one called `.babelrc`. If so, rename that file to `babel.config.js` and make the changes needed to match the updated file. You might need to configure additional plugins if you had some before.

**Comment by oxbits** [comment]
it would be good if there were a link to the entire file in case someone does not have it to modify.

**Comment by pvinis** [comment]
But it does make sense to have a link to the full file. I will open the issue again.

For now, you can just go to the purge repo, checkout the correct release/x.y.z branch, and see the file there.

**Comment by lucasbento** [comment]
@pvinis: this has been reported as a feature request on #79, I would say we can close this one as it's aiming to solve the problem specified here.

**Comment by pvinis** [comment]
indeed. i forgot about the other issue.
