### ISSUE TITLE
View full file contents

### ISSUE THREAD

**Issue by mausworks** [react-native-community/upgrade-helper#79]
# Feature request

Instead of viewing just the diff between different file version, why not just allow the user to view the full contents of the file? I.e. "view raw"

## Why it is needed

Some diffs are just not that useful 🤷‍♀ 

For instance, the `.flowconfig`-file is (in my case) never manually edited. The diff is not very helpful in this case, because all I want is just the "new version of the file".

## Possible implementation

Add a "view raw" or "view file" to the "header" of the diff.

![image](https://user-images.githubusercontent.com/8259221/62128852-9f2fd100-b2d5-11e9-9860-0254b5a50a89.png)

**Comment by mausworks** [comment]
I can submit a PR for this if you think this is a good idea.

**Comment by lucasbento** [comment]
This has also been reported on #78, I would gladly accept a PR for this, just a suggestion to change `View raw` to `View file`.
