### ISSUE TITLE
Add Podfile change for iOS

### ISSUE THREAD

**Issue by Matrixbirds** [react-native-community/upgrade-helper#95]
Every time, When I m try to upgrade to the new react native version, I would speed too many times to fix compilation environment, If we can provide the correct `Podfile` configuration for react-native dependency. This toolkit will be more usefully.

**Comment by kelset** [comment]
I am not sure I understand - in the "diff" we show the Podfile when changes are needed.

What do you want to be different? Like, to be able to download the "new" podfile? 🤔

**Comment by Matrixbirds** [comment]
Sure, could be download as well can resolve this problem.

**Comment by pvinis** [comment]
I also don't understand. https://react-native-community.github.io/upgrade-helper/?from=0.60.5&to=0.61.0-rc.0 here for example, you can see the changes on the Podfile. You can also click `View file` to see the whole file in the latest version of it. You can get that, and then add whatever else you need in there.

Would that solve your problem?

**Comment by Matrixbirds** [comment]
@pvinis thx for replying, but you cannot find the Podfile diff before 0.60.x version

**Comment by lucasbento** [comment]
@Matrixbirds: that's because we started supporting CocoaPods out-of-the-box on `0.60` release, therefore we only have diff after that version.

**Comment by pvinis** [comment]
Exactly. So if you had a podfile before that, then it's up to you to merge your pre-existing podfile with the 0.60.0 podfile. It usually is not so bad, it's simple.

**Comment by lucasbento** [comment]
@Matrixbirds: I'm closing this issue since it's quite clear why `Podfile` is not existent on versions before `0.60`, please don't hesitate on opening another issue if you feel the need to.
